# Dependencies
markdown:         kramdown

# Setup
title:            Endonymous
tagline:          "Le roman graphique qui parle d'endométriose"

description:      "Deux ans plus tard est un roman graphique autobiographique sur l'endométriose."
url:              https://endonymous.fr

baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Isabelle Dulin'
  url:            https://twitter.com/Endonym0us

permalink: /:categories/:title:output_ext

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  - scope:
      path: "assets/images/partie7/png"
    values:
      partie: 7
  - scope:
      path: "assets/images/reseaux"
    values:
      reseaux: true